version: "3.8"

services:
  db:
    image: bjorn-ai-db:1.0          # <<-- SÓ MUDEI ESSA LINHA
    container_name: bjorn-ai-db-1
    environment:
      POSTGRES_DB: bjorn_db
      POSTGRES_USER: bjorn
      POSTGRES_PASSWORD: bjorn123
    ports:
      - "5433:5432"  # host:5433 -> container:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bjorn -d bjorn_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: bjorn-ai:latest
    depends_on:
      db:
        condition: service_healthy

    # carrega as variáveis como OPENAI_API_KEY do seu .env
    env_file:
      - .env

    environment:
      # aponta para o serviço "db" e para o banco bjorn_db
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bjorn_db
      SPRING_DATASOURCE_USERNAME: bjorn
      SPRING_DATASOURCE_PASSWORD: bjorn123

      # dentro do container
      BJORN_STORAGE_DIR: /data/storage

    ports:
      - "8080:8080"

    # se quiser volume anônimo:
    volumes:
      - app-storage:/data/storage
    # ou, se quiser usar o D:\RAG do host (como você fazia antes), troque por:
    # volumes:
    #   - "D:/RAG:/data/storage"

    restart: unless-stopped

volumes:
  pgdata:
  app-storage:
